import { Article, HardwareSpec } from "@/types";

export const PROJECT_META = {
  title: "Computación Paralela & Sistemas Distribuidos",
  shortTitle: "Universidad del Istmo - Campus Tehuantepec",
  institution: "Universidad del Istmo",
  faculty: "Ingeniería en Computación",
  semester: "Ciclo 2025-2026 B",
  mentor: {
    name: "Dr. J. Jesùs Arellano Pimentel",
    role: "Profesor Titular & Mentor de Investigación",
    photo : "/mentor.jpg", 
  },
  members: [
    { name: "Jeycson Gabriel López Hernández", role: "Estudiante Ing. Computación", photo: "/jeycson.jpg"},
    { name: "Jeovani Pacheco Rueda", role: "Estudiante Ing. Computación", photo: "/jeovani.jpg" },
    { name: "Mariana Palacios Trinidad", role: "Estudiante Ing. Computación", photo: "/mariana.jpg" },
    { name: "Jairo Iván Hipolito Morales", role: "Estudiante Ing. Computación", photo: "/jairo.jpg" },
  ],
  abstract:
    "Este proyecto documenta una serie de experimentos controlados sobre el comportamiento de aplicaciones de cómputo intensivo bajo distintos paradigmas de paralelismo: SIMD, OpenMP, hilos POSIX y CPython. Evaluamos SpeedUp, eficiencia y overhead en entornos de hardware heterogéneo, con el objetivo de establecer métricas reproducibles y recomendaciones prácticas para el diseño de software de alto rendimiento.",
  githubUrl: "https://github.com/Jeycson/Analisis_Evaluacion_PPI",
};

export const HARDWARE_SPECS: HardwareSpec[] = [
  {
    id: "env-a",
    name: "Entorno A — Laptop 1 (Windows)",
    role: "laptop",
    cpu: "Intel Core i5-1135G7",
    cores: 4,
    threads: 8,
    cacheL1: "80 KB × 4 núcleos",
    cacheL2: "1.25 MB × 4 núcleos",
    cacheL3: "8.0 MB compartida",
    ram: "20 GB DDR4-3200",
    os: "Windows 11 Home Single Language, Edición 25H2, Versión 26200.8457, Nativo de 64 bits",
    notes: "Hyperthreading habilitado durante todas las pruebas. Ejecución nativa.",
  },
  {
    id: "env-b",
    name: "Entorno B — Laptop 1 (Fedora)",
    role: "laptop",
    cpu: "Intel Core i5-1135G7",
    cores: 4,
    threads: 8,
    cacheL1: "80 KB × 4 núcleos",
    cacheL2: "1.25 MB × 4 núcleos",
    cacheL3: "8.0 MB compartida",
    ram: "20 GB DDR4-3200",
    os: "Fedora Workstation 42, GNOME Version 48, Kernel Version Linux 6.14.6-300.fc42.x86_64, Nativo",
    notes: "Hyperthreading habilitado durante todas las pruebas. Ejecución nativa.",
  },
  {
    id: "env-c",
    name: "Entorno C — Laptop 2 (Windows)",
    role: "laptop",
    cpu: "AMD Ryzen 5 7520U with Radeon Graphics (2.80 GHz)",
    cores: 4,
    threads: 8,
    cacheL1: "256kb",
    cacheL2: "2.0Mb",
    cacheL3: "4.0Mb",
    ram: "8 GB DDR4-3200",
    os: "Windows 11 Home Single Language, Edición 25H2, Versión 26200.8039, Serie PF4DXH1X",
    notes: "Ejecución nativa",
  },
  {
    id: "env-d",
    name: "Entorno D — Laptop 2 (Ubuntu)",
    role: "laptop",
    cpu: "AMD Ryzen 5 7520U with Radeon Graphics (2.80 GHz)",
    cores: 4,
    threads: 8,
    cacheL1: "256kb",
    cacheL2: "2.0Mb",
    cacheL3: "4.0Mb",
    ram: "8 GB DDR4-3200",
    os: "Ubuntu 24.04.4 LTS, GNOME Version 46, Kernel Version Linux 6.17.0-20-generic",
    notes: "Firmware Version L1CN30WW. Ejecución nativa.",
  },
  {
    id: "env-e",
    name: "Entorno E — Laptop 3 (Windows)",
    role: "laptop",
    cpu: "13th Gen Intel(R) Core(TM) i3-1305U (1.60 GHz)",
    cores: 5,
    threads: 6,
    cacheL1: "464kb",
    cacheL2: "3.2Mb",
    cacheL3: "10.0Mb",
    ram: "8 GB LPDDR5",
    os: "Windows 11 Home Single Language, Edición 25H2, Versión 26200.8524, Serie PF4MAYP8",
    notes: "Ejecución nativa.",
  },
  {
    id: "env-f",
    name: "Entorno F — Laptop 3 (Fedora)",
    role: "workstation",
    cpu: "13th Gen Intel(R) Core(TM) i3-1305U x5",
    cores: 5,
    threads: 1,
    cacheL1: "160kb",
    cacheL2: "10.0Mb",
    cacheL3: "50.0Mb",
    ram: "4.8 GBi",
    os: "Fedora Linux 44 (Workstation Edition), GNOME Version 50, Kernel Version Linux 6.17.0-20-generic",
    notes: "Ejecución virtualizada.",
  },
];

export const ARTICLES: Article[] = [
  {
    slug: "caso-a-variacion-carga",
    title: "Caso A: Variación de Carga de Trabajo",
    subtitle:
      "¿Cómo se van a comportar los tiempos de ejecución si se mantiene el código, pero se varía el tamaño de la imagen a procesar, en cada configuración? Y ¿existe una variación y si existe cómo se podría explicar tal variación observada? ",
    category: "Análisis de Rendimiento",
    tags: ["OpenMP", "SIMD", "Python"],
    authors: [
      {
        name: "Jeycson Gabriel López Hernández",
        role: "Estudiante de Ing. Computación",
        institution: "Unistmo",
      }
    ],
    date: "2026-06-6",
    readingTime: 12,
    abstract:
      "Exploramos cómo el tamaño del dataset afecta el rendimiento de implementaciones paralelas en OpenMP, SIMD y Python. Encontramos que entre mayor es el tamaño de la imagen, mayor es el tiempo de procesamiento que le tomara a cada configuración.",
    hardware: ["env-c"],
  },
  {
    slug: "caso-b-overhead-hilos",
    title: "Caso B: Variación de número de hilos con el mismo tamaño de imagen",
    subtitle: "Análisis de escalamiento fuerte, overhead de sincronización y el impacto del GIL bajo una carga de trabajo constante.",
    category: "Sistemas de Hilos",
    tags: ["POSIX Threads", "Thread Pool", "Latencia", "Overhead", "Linux", "OpenMP", "SIMD", "Python"],
    authors: [
      {
        name: "Jeovani Pacheco Rueda",
        role: "Estudiante de Ing. Computación",
        institution: "Unistmo",
      },
    ],
    date: "2026-06-07",
    readingTime: 9,
    abstract: "Medimos con nanosegundos de precisión el costo de creación, sincronización y destrucción de hilos POSIX.",
    hardware: ["env-a"],
  },
  {
    slug: "caso-c-comparacion-linux-virtualbox-windows11",
    title: "Caso C: Comparación de Tiempos de Ejecución: Linux en VirtualBox vs. Windows 11",
    subtitle:
      "¿Si Linux está ejecutándose en Virtual Box, que a su vez está instalada en Windows 11, cómo se espera que se comporte en los tiempos de ejecución de un sistema respecto a otro para una misma configuración de hilos y tamaño de imagen?",
    category: "Comparación de Sistemas Operativos",
    tags: ["OpenMP", "Python", "VirtualBox", "Windows 11", "Linux"],
    authors: [
      {
        name: "Mariana Palacios Trinidad",
        role: "Estudiante de Ing. Computación",
        institution: "Unistmo",
      },
    ],
    date: "2026-06-07",
    readingTime: 14,
    abstract:
    "Análisis comparativo del rendimiento entre Windows 11 nativo y Linux Fedora 43 ejecutado en VirtualBox. Utilizando OpenMP con dos hilos y una imagen de 2480×1860 píxeles, demostramos que la capa de virtualización introduce un overhead que incrementa los tiempos de ejecución y la variabilidad del sistema invitado, confirmando que el acceso directo al hardware proporciona un mejor desempeño.",
    hardware: ["env-e", "env-f",],
  },
  {
    slug: "caso-d-cache-misses",
    title: "Caso D: Fallos de Caché y Localidad de Datos",
    subtitle:
      "Análisis de acceso a memoria con perf y Valgrind/Cachegrind en algoritmos de álgebra lineal",
    category: "Arquitectura de Memoria",
    tags: ["Cache", "perf", "Cachegrind", "BLAS", "Localidad"],
    authors: [
      {
        name: "Jairo ",
        role: "Estudiante de Ing. Computación",
        institution: "Unistmo",
      },
    ],
    date: "2025-04-22",
    readingTime: 16,
    abstract:
      "Utilizamos perf stat y Cachegrind para perfilar la tasa de L1/L2/L3 cache misses en implementaciones naive vs. optimizadas de multiplicación de matrices. El tiling por bloques reduce las faltas de L3 hasta un 87%.",
    hardware: ["env-a", "env-c"],
  },
  {
    slug: "caso-e-speedup-so-variacion-carga",
    title: "Caso E: Variación de tamaño de la imagen con el mismo número de hilos en Windows y Linux",
    subtitle: "Evaluación del SpeedUp relativo entre Windows 11 y Linux al variar el tamaño de la imagen con un mismo esquema de paralelismo.",
    category: "Comparación de Sistemas Operativos",
    tags: ["Windows 11", "Ubuntu Linux", "SpeedUp", "OpenMP", "SIMD", "Python"],
    authors: [
      {
        name: "Jeycson Gabriel López Hernández",
        role: "Estudiante Ing. Computación",
        institution: "Unistmo",
      },
    ],
    date: "2026-06-07",
    readingTime: 30,
    abstract: "Este reporte ...",
    hardware: ["env-c", "env-d"], 
  },
  {
    slug: "caso-f-speedup-sistemas-operativos",
    title: "Caso F: Variación de número de hilos con el mismo tamaño de imagen en Windows y Linux",
    subtitle: "Evaluación del impacto del planificador de SO en factores de aceleración (SpeedUp)",
    category: "Análisis de Rendimiento",
    tags: ["Windows 11", "Fedora Linux", "SpeedUp", "Overhead", "GIL", "OpenMP", "SIMD"],
    authors: [
      {
        name: "Jeovani Pacheco Rueda",
        role: "Estudiante Ing. Computación",
        institution: "Unistmo",
      },
    ],
    date: "2026-06-07",
    readingTime: 12,
    abstract: "Este reporte evalúa el impacto crítico del planificador de procesos en Windows 11 frente a Linux al incrementar la densidad de hilos (de 2 a 16) bajo una carga de trabajo constante. Los resultados demuestran de forma empírica que mantener un tamaño de imagen fijo e intensivo induce pérdidas severas de eficiencia por overhead de sincronización a partir de los 4 hilos. Asimismo, se evidencia un falso espejismo de escalabilidad en entornos interpretados, donde Python bajo Linux registra un SpeedUp relativo de 1.66 debido a la profunda ineficiencia de su estado base , mientras que las implementaciones nativas en C (OpenMP y SIMD) mantienen el rendimiento absoluto óptimo por debajo del milisegundo.",
    hardware: ["env-a", "env-b"], 
  },
];
